#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: chef-solo:install: "Install chef solo and a configuration package which contains the chef recipies"
#/ usage: rerun chef-solo:install  --role <> [ --pkgurl <>] [ --cfgpkgurl <>] 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh install || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: chef-solo:install. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ROLE PKGURL CFGPKGURL

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
if [[ $(id -u) = "0" ]]; then
    SUDO=""
else
    SUDO="sudo "
fi
${SUDO}yum update -y ruby ruby-devel rubygems
if [[ ".amzn1" = "$(rpm --eval %{?dist})" ]]; then
  ${SUDO}yum update -y ruby-ri ruby-rdoc
else
  ${SUDO}yum update -y ruby-shadow rubygem-rdoc 
fi
${SUDO}yum update -y ${PKGURL:-"chef-solo"}
${SUDO}yum update -y ${CFGPKGURL:-"chef-${ROLE}-cfg.rpm"}
# - - -

# Done. Exit with last command exit status.
exit $?

